#!/usr/bin/env python
# vim:fileencoding=utf-8:noet

import argparse
import sys
import re
import os.path

try:
	import fontforge
except ImportError:
	sys.stderr.write('The required FontForge modules could not be loaded.\n\n')
	sys.stderr.write('You need FontForge with Python bindings for this script to work.\n')
	sys.exit(1)

def get_argparser(ArgumentParser=argparse.ArgumentParser):
	parser = ArgumentParser(
		description=('Font builder'
		             'Requires FontForge with Python bindings. ')
	)
	parser.add_argument('target_font', help='font files to build', metavar='font',
	                    type=argparse.FileType('rb'))
	return parser

def build_one_font(font):
	output_name = font.name[:-7]+'.bdf'
	font = fontforge.open(font.name)
	font.generate(output_name)


def main(argv):
	args = get_argparser().parse_args(argv)
	return build_one_font(args.target_font)

raise SystemExit(main(sys.argv[1:]))
